---
proxy-providers:
  ETH1:
    type: file
    path: "./proxy_provider/wan1.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
proxy-groups:
- name: DIRECT-WAN1
  type: select
  disable-udp: false
  proxies:
  - DIRECT
- name: GAME
  type: select
  disable-udp: false
  proxies:
  - DIRECT-WAN1
  - PROXY-WAN1
- name: PROXY-WAN1
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - ETH1
  url: http://www.gstatic.com/generate_204
  interval: '300'
dns:
  nameserver:
  - 140.213.88.253
  - 140.213.88.254
  - 10.109.142.108
  - 8.8.8.8
  - 8.8.4.4
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:7874
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  default-nameserver:
  - 140.213.88.253
  - 140.213.88.254
  - 10.109.142.108
  - 8.8.8.8
  - 8.8.4.4
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: '123456'
bind-address: "*"
external-ui: "/usr/share/openclash/dashboard"
ipv6: false
profile:
  store-selected: true
  store-fake-ip: true
rule-providers:
  iklan:
    type: http
    behavior: classical
    path: "./rule_provider/iklan.yaml"
    url: https://raw.githubusercontent.com/juni91/open_clash/main/single_modem/rule_provider/iklan.yaml
    interval: 86400
  umum:
    type: http
    behavior: classical
    path: "./rule_provider/umum.yaml"
    url: https://raw.githubusercontent.com/juni91/open_clash/main/single_modem/rule_provider/umum.yaml
    interval: 86400
  game:
    type: http
    behavior: classical
    path: "./rule_provider/gaming.yaml"
    url: https://raw.githubusercontent.com/juni91/open_clash/main/single_modem/rule_provider/gaming.yaml
    interval: 86400
rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- RULE-SET,iklan,REJECT
- RULE-SET,umum,PROXY-WAN1
- RULE-SET,game,GAME
- MATCH,GLOBAL
